import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js";
import { getFirestore, collection, addDoc, getDocs, query, where, doc, updateDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js";

const app = initializeApp({ apiKey: "AIzaSyDpawG59DxmrdHOxmglW7Ez3HcefvO5b6E", authDomain: "talaba-app.firebaseapp.com", projectId: "talaba-app", storageBucket: "talaba-app.firebasestorage.app", messagingSenderId: "642352039580", appId: "1:642352039580:web:307d32a9c8eb3c2b388f59" });
const db = getFirestore(app);

window.showToast = (msg, type = 'success') => {
    let container = document.getElementById('toast-container');
    if(!container) { container = document.createElement('div'); container.id = 'toast-container'; container.className = 'fixed bottom-5 left-1/2 transform -translate-x-1/2 z-[9999] flex flex-col gap-2 pointer-events-none'; document.body.appendChild(container); }
    const toast = document.createElement('div'); toast.className = `px-6 py-3 rounded-xl shadow-2xl text-white font-bold text-center transform transition-all duration-300 translate-y-10 opacity-0 ${type === 'success' ? 'bg-green-600' : 'bg-red-600'}`; toast.innerText = msg; container.appendChild(toast);
    setTimeout(() => toast.classList.remove('translate-y-10', 'opacity-0'), 10);
    setTimeout(() => { toast.classList.add('translate-y-10', 'opacity-0'); setTimeout(() => toast.remove(), 300); }, 3000);
};

const userName = localStorage.getItem('userName'); const userId = localStorage.getItem('userId');
if(userName) { const tNav = document.getElementById('topNavWelcome'); if(tNav) tNav.innerText = `مرحبا بالأستاذ الكريم: ${userName}`; }

window.logout = () => { localStorage.clear(); window.location.href = '../index.html'; };
window.toggleSidebar = () => { document.getElementById('sidebar').classList.toggle('translate-x-full'); };
window.showSection = (id) => { document.querySelectorAll('.section-content').forEach(el => el.classList.remove('section-active')); document.getElementById(`section-${id}`).classList.add('section-active'); if(window.innerWidth < 768) document.getElementById('sidebar').classList.add('translate-x-full'); };
window.openModal = (id) => document.getElementById(id).classList.remove('hidden');
window.closeModal = (id) => { document.getElementById(id).classList.add('hidden'); const form = document.querySelector(`#${id} form`); if(form) { form.reset(); const hid = form.querySelector('input[type="hidden"]'); if(hid) hid.value = ''; } };

window.deleteRecord = async (col, id, refreshFunc) => { if(confirm('هل أنت متأكد من الحذف نهائياً؟')) { try { await deleteDoc(doc(db, col, id)); window.showToast('تم الحذف بنجاح'); refreshFunc(); } catch(e) { window.showToast('خطأ أثناء الحذف', 'error'); } } };

document.getElementById('changePassForm').addEventListener('submit', async (e) => { e.preventDefault(); try { await updateDoc(doc(db, "users", userId), { password: document.getElementById('newPass').value }); window.showToast('تم تغيير كلمة المرور!'); window.closeModal('changePassModal'); } catch(err) { window.showToast('حدث خطأ', 'error');} });

async function loadTeacherSubjects() { try { const snap = await getDocs(query(collection(db, "subjects"), where("teacherName", "==", userName))); let opts = '<option value="">-- اختر المادة --</option>'; snap.forEach(doc => { opts += `<option value="${doc.data().name}">${doc.data().name}</option>`; }); document.querySelectorAll('.teacher-subjects-dropdown').forEach(sel => sel.innerHTML = opts); } catch (e) { } }

// سجل الغياب
document.getElementById('attendanceDate').valueAsDate = new Date();
async function loadStudents() { const tbody = document.getElementById('attendanceTableBody'); const snap = await getDocs(query(collection(db, "users"), where("role", "==", "طالب"))); tbody.innerHTML = ''; snap.forEach(doc => { tbody.innerHTML += `<tr class="border-b student-row" data-id="${doc.id}" data-name="${doc.data().name}"><td class="p-4 font-semibold">${doc.data().name}</td><td class="p-4 text-center"><label class="text-green-600 mx-2"><input type="radio" name="st_${doc.id}" value="حاضر" checked> حاضر</label><label class="text-red-600 mx-2"><input type="radio" name="st_${doc.id}" value="غائب"> غائب</label></td></tr>`; }); }
document.getElementById('saveAttendanceBtn').addEventListener('click', async () => { const subj = document.getElementById('attendanceSubject').value; if(!subj) return window.showToast('الرجاء اختيار المادة', 'error'); let records = []; document.querySelectorAll('.student-row').forEach(row => { records.push({ studentId: row.getAttribute('data-id'), studentName: row.getAttribute('data-name'), status: document.querySelector(`input[name="st_${row.getAttribute('data-id')}"]:checked`).value }); }); await addDoc(collection(db, "attendance"), { date: document.getElementById('attendanceDate').value, records, teacherId: userId, teacherName: userName, subjectName: subj, timestamp: new Date() }); window.showToast('تم الحفظ والإرسال للمدير!'); loadTeacherAttendanceHistory(); });

async function loadTeacherAttendanceHistory() { const list = document.getElementById('attendanceHistoryList'); if(!list) return; const snap = await getDocs(query(collection(db, "attendance"), where("teacherName", "==", userName))); let arr = []; snap.forEach(d => arr.push({id: d.id, ...d.data()})); arr.sort((a,b) => b.timestamp - a.timestamp); list.innerHTML = ''; arr.forEach(a => { const absents = a.records.filter(r => r.status === 'غائب').map(r => r.studentName); const absentText = absents.length > 0 ? absents.join('، ') : 'الجميع حاضرون'; list.innerHTML += `<div class="bg-green-50 p-4 rounded-xl border border-green-200 shadow-sm"><div class="flex justify-between items-center border-b border-green-200 pb-2 mb-2"><span class="font-bold text-green-800">${a.date} | ${a.subjectName}</span><button onclick="window.deleteRecord('attendance', '${a.id}', window.loadTeacherAttendanceHistory)" class="text-red-500 font-bold text-sm">حذف</button></div><p class="text-sm font-semibold text-gray-700"><span class="text-red-600">الغياب:</span> ${absentText}</p></div>`; }); }
window.loadTeacherAttendanceHistory = loadTeacherAttendanceHistory;

// دفتر النصوص
document.getElementById('journalDate').valueAsDate = new Date(); 
document.getElementById('addJournalForm').addEventListener('submit', async (e) => { e.preventDefault(); const id = document.getElementById('editJournalId').value; const data = { date: document.getElementById('journalDate').value, subjectName: document.getElementById('journalSubject').value, content: document.getElementById('journalContent').value, teacherName: userName }; if(id) { await updateDoc(doc(db, "journals", id), data); window.showToast('تم التعديل'); } else { await addDoc(collection(db, "journals"), { ...data, timestamp: new Date() }); window.showToast('تم التدوين'); } window.closeModal('addJournalModal'); loadJournals(); });
window.editJournal = (id, date, subj, content) => { document.getElementById('editJournalId').value = id; document.getElementById('journalDate').value = date; document.getElementById('journalSubject').value = subj; document.getElementById('journalContent').value = content; window.openModal('addJournalModal'); };
async function loadJournals() { const list = document.getElementById('journalsList'); const snap = await getDocs(query(collection(db, "journals"), where("teacherName", "==", userName))); let arr = []; snap.forEach(d => arr.push({id: d.id, ...d.data()})); arr.sort((a,b) => b.timestamp - a.timestamp); list.innerHTML = ''; arr.forEach(j => { list.innerHTML += `<div class="bg-white p-5 rounded-xl border-r-4 border-orange-500 shadow-sm"><div class="flex justify-between items-center"><span class="font-bold text-orange-800">${j.date} | ${j.subjectName}</span><div><button onclick="window.editJournal('${j.id}','${j.date}','${j.subjectName}','${j.content.replace(/'/g, "\\'")}')" class="text-blue-500 font-bold text-sm mx-2">تعديل</button><button onclick="window.deleteRecord('journals', '${j.id}', window.loadJournals)" class="text-red-500 font-bold text-sm">حذف</button></div></div><p class="text-gray-700 bg-orange-50 p-3 rounded mt-2">${j.content}</p></div>`; }); }
window.loadJournals = loadJournals;

// التكليفات المعتادة وإنجازاتها
document.getElementById('addAssignmentForm').addEventListener('submit', async (e) => { e.preventDefault(); await addDoc(collection(db, "assignments"), { subjectName: document.getElementById('assSubject').value, title: document.getElementById('assTitle').value, description: document.getElementById('assDesc').value, teacherName: userName, timestamp: new Date() }); window.closeModal('addAssignmentModal'); loadAssignments(); window.showToast('تم نشر التكليف'); });
async function loadAssignments() { const list = document.getElementById('assignmentsList'); const snap = await getDocs(query(collection(db, "assignments"), where("teacherName", "==", userName))); let arr = []; snap.forEach(d => arr.push({id: d.id, ...d.data()})); arr.sort((a,b) => b.timestamp - a.timestamp); list.innerHTML = ''; arr.forEach(doc => { const safeTitle = doc.title ? doc.title.replace(/'/g, "\\'").replace(/"/g, "&quot;") : 'تكليف'; list.innerHTML += `<div class="bg-white p-6 rounded-xl border border-blue-100 flex flex-col justify-between"><div><span class="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded font-bold">${doc.subjectName}</span><h3 class="text-xl font-bold mt-2">${doc.title}</h3><p class="mt-2 text-sm text-gray-600 bg-blue-50 p-3 rounded">${doc.description}</p></div><div class="mt-4 flex justify-between items-center"><button onclick="window.viewSubmissions('${doc.id}', '${safeTitle}')" class="bg-blue-600 hover:bg-blue-700 text-white font-bold px-4 py-2 rounded-lg text-sm shadow">📥 عرض إنجازات الطلبة</button><button onclick="window.deleteRecord('assignments', '${doc.id}', window.loadAssignments)" class="text-red-500 font-bold text-sm">حذف</button></div></div>`; }); }
window.loadAssignments = loadAssignments;
window.viewSubmissions = async (assId, title) => { document.getElementById('submissionsModalTitle').innerText = 'إنجازات التكليف: ' + title; const list = document.getElementById('assignmentSubmissionsList'); list.innerHTML = '<p class="text-center font-bold p-4">جاري تحميل إنجازات الطلبة...</p>'; window.openModal('assignmentSubmissionsModal'); try { const snap = await getDocs(query(collection(db, "submissions"), where("assignmentId", "==", assId))); list.innerHTML = ''; if(snap.empty) { list.innerHTML = '<p class="text-center text-gray-500 font-bold p-4">لم يقم أي طالب بتسليم إنجازه حتى الآن.</p>'; return; } snap.forEach(d => { const sub = d.data(); list.innerHTML += `<div class="bg-blue-50 p-4 rounded-xl border border-blue-200"><h4 class="font-bold text-blue-900 border-b border-blue-200 pb-2 mb-2">🎓 الطالب: ${sub.studentName}</h4><p class="text-gray-800 font-medium whitespace-pre-wrap">${sub.answerText}</p></div>`; }); } catch(e) { list.innerHTML = '<p class="text-center text-red-500 p-4">حدث خطأ</p>'; } };

// الوثائق
document.getElementById('addDocumentForm').addEventListener('submit', async (e) => { e.preventDefault(); await addDoc(collection(db, "documents"), { subjectName: document.getElementById('docSubject').value, title: document.getElementById('docTitle').value, description: document.getElementById('docDesc').value, link: document.getElementById('docLink').value, teacherName: userName, timestamp: new Date() }); window.closeModal('addDocumentModal'); loadDocuments(); window.showToast('تم رفع الوثيقة'); });
async function loadDocuments() { const list = document.getElementById('documentsList'); const snap = await getDocs(query(collection(db, "documents"), where("teacherName", "==", userName))); let arr = []; snap.forEach(d => arr.push({id: d.id, ...d.data()})); arr.sort((a,b) => b.timestamp - a.timestamp); list.innerHTML = ''; arr.forEach(d => { list.innerHTML += `<div class="bg-white p-5 rounded-xl border-r-4 border-teal-500 flex justify-between items-center"><div><h3 class="font-bold">📁 ${d.subjectName}: ${d.title}</h3><p class="text-sm text-gray-500 my-1">${d.description}</p><a href="${d.link}" target="_blank" class="text-teal-600 underline font-bold text-sm">عرض المرفق</a></div><button onclick="window.deleteRecord('documents', '${d.id}', window.loadDocuments)" class="bg-red-50 text-red-500 px-3 py-1 rounded font-bold text-sm">حذف</button></div>`; }); }
window.loadDocuments = loadDocuments;

// ================= الاختبارات والنتائج (الدرع المصفح) =================
window.generateQuizForms = () => { const count = parseInt(document.getElementById('quizCount').value); const container = document.getElementById('questionsContainer'); const saveBtn = document.getElementById('saveQuizBtn'); if(count === 0) { container.innerHTML = 'اختر عدد الأسئلة للبدء...'; saveBtn.classList.add('hidden'); return; } saveBtn.classList.remove('hidden'); container.innerHTML = ''; for(let i=1; i<=count; i++) { container.innerHTML += `<div class="bg-purple-50 p-4 rounded-xl border border-purple-200 mb-4"><div class="flex justify-between mb-3"><h4 class="font-bold text-purple-900">السؤال ${i}</h4><select id="qType_${i}" class="px-3 py-1 rounded border" onchange="window.toggleQType(${i})"><option value="mcq">اختيار من متعدد</option><option value="tf">صحيح / خطأ</option></select></div><input type="text" id="qText_${i}" class="w-full mb-3 px-3 py-2 rounded focus:ring-2 focus:ring-purple-500" placeholder="اكتب نص السؤال هنا..." required><div id="mcqContainer_${i}" class="grid grid-cols-2 gap-2"><input type="text" id="qOpt_${i}_1" class="px-3 py-2 rounded bg-green-50 border-green-300" placeholder="الإجابة الصحيحة" required><input type="text" id="qOpt_${i}_2" class="px-3 py-2 rounded border" placeholder="خيار خاطئ 1" required><input type="text" id="qOpt_${i}_3" class="px-3 py-2 rounded border" placeholder="خيار خاطئ 2"><input type="text" id="qOpt_${i}_4" class="px-3 py-2 rounded border" placeholder="خيار خاطئ 3"></div><div id="tfContainer_${i}" class="hidden"><select id="qTfAns_${i}" class="w-full px-3 py-2 rounded border"><option value="صحيح">صحيح</option><option value="خطأ">خطأ</option></select></div></div>`; } };
window.toggleQType = (i) => { const type = document.getElementById(`qType_${i}`).value; if(type === 'mcq') { document.getElementById(`mcqContainer_${i}`).classList.remove('hidden'); document.getElementById(`tfContainer_${i}`).classList.add('hidden'); } else { document.getElementById(`mcqContainer_${i}`).classList.add('hidden'); document.getElementById(`tfContainer_${i}`).classList.remove('hidden'); document.getElementById(`qOpt_${i}_1`).required = false; document.getElementById(`qOpt_${i}_2`).required = false; } };
window.saveQuiz = async () => { const title = document.getElementById('quizTitle').value; const subj = document.getElementById('quizSubject').value; const count = parseInt(document.getElementById('quizCount').value); const deadline = document.getElementById('quizDeadline').value; if(!title || !subj || !deadline) return window.showToast('الرجاء إكمال جميع البيانات والموعد النهائي', 'error'); let questions = []; for(let i=1; i<=count; i++) { const qText = document.getElementById(`qText_${i}`).value; const qType = document.getElementById(`qType_${i}`).value; let qData = { text: qText, type: qType, points: 1 }; if(qType === 'mcq') { const opt1 = document.getElementById(`qOpt_${i}_1`).value; qData.correctAnswer = opt1; qData.options = [opt1, document.getElementById(`qOpt_${i}_2`).value, document.getElementById(`qOpt_${i}_3`).value, document.getElementById(`qOpt_${i}_4`).value].filter(v=>v); } else { qData.correctAnswer = document.getElementById(`qTfAns_${i}`).value; qData.options = ["صحيح", "خطأ"]; } questions.push(qData); } await addDoc(collection(db, "quizzes"), { title: title, subjectName: subj, teacherName: userName, deadline: deadline, totalQuestions: count, maxScore: count, questions: questions, timestamp: new Date() }); window.showToast('تم نشر الاختبار بنجاح!'); window.closeModal('addQuizModal'); loadQuizzes(); };

async function loadQuizzes() { 
    const list = document.getElementById('quizzesList'); const snap = await getDocs(query(collection(db, "quizzes"), where("teacherName", "==", userName))); 
    let arr = []; snap.forEach(d => arr.push({id: d.id, ...d.data()})); arr.sort((a,b) => b.timestamp - a.timestamp); list.innerHTML = ''; 
    arr.forEach(q => { 
        // حماية من الأخطاء في الاختبارات القديمة
        const safeTitle = q.title ? q.title.replace(/'/g, "\\'").replace(/"/g, "&quot;") : 'اختبار';
        const deadlineTxt = q.deadline ? q.deadline.replace('T', ' ') : 'بدون موعد (مفتوح)';
        
        list.innerHTML += `<div class="bg-white p-5 rounded-xl border border-purple-200 flex flex-col justify-between shadow-sm"><div><span class="text-xs text-purple-800 font-bold bg-purple-100 px-2 py-1 rounded">${q.subjectName || 'مادة'}</span><h3 class="text-xl font-bold mt-3 text-purple-900">${q.title}</h3><p class="text-xs text-red-600 font-bold mt-2">يغلق في: ${deadlineTxt}</p></div><div class="flex justify-between items-center mt-4"><button onclick="window.viewQuizResults('${q.id}', '${safeTitle}')" class="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg font-bold text-sm shadow flex-1 text-center">📊 عرض نتائج الطلبة</button><button onclick="window.deleteRecord('quizzes', '${q.id}', window.loadQuizzes)" class="text-red-500 font-bold text-sm bg-red-50 px-3 py-2 rounded-lg mr-2">حذف</button></div></div>`; 
    }); 
}
window.loadQuizzes = loadQuizzes;

window.sendResultToAdmin = () => { window.showToast('تم إرسال واعتماد النتيجة للإدارة وللطالب بنجاح!', 'success'); };

window.viewQuizResults = async (quizId, quizTitle) => { 
    document.getElementById('resultsModalTitle').innerText = 'نتائج: ' + quizTitle; 
    const tbody = document.getElementById('quizResultsBody'); 
    tbody.innerHTML = '<tr><td colspan="3" class="text-center p-4 font-bold">جاري الجلب من قاعدة البيانات...</td></tr>'; 
    window.openModal('quizResultsModal'); 
    try { 
        const snap = await getDocs(query(collection(db, "quiz_results"), where("quizId", "==", quizId))); 
        tbody.innerHTML = ''; 
        if(snap.empty) { tbody.innerHTML = '<tr><td colspan="3" class="text-center text-gray-500 p-4 font-bold">لم يقم أي طالب بإنجاز هذا الاختبار حتى الآن.</td></tr>'; return; } 
        snap.forEach(doc => { 
            const res = doc.data(); 
            tbody.innerHTML += `<tr class="border-b hover:bg-purple-50"><td class="p-3 font-bold text-gray-800">${res.studentName || 'طالب'}</td><td class="p-3 font-extrabold text-purple-700 text-lg" dir="ltr">${res.score}/${res.maxScore}</td><td class="p-3 text-center"><button onclick="window.sendResultToAdmin()" class="bg-green-500 hover:bg-green-600 text-white px-3 py-1 rounded-lg text-sm shadow">إرسال واعتماد</button></td></tr>`; 
        }); 
    } catch(err) { tbody.innerHTML = '<tr><td colspan="3" class="text-red-500 text-center p-4">حدث خطأ أثناء الجلب</td></tr>'; } 
};

loadTeacherSubjects().then(() => { loadStudents(); loadJournals(); loadAssignments(); loadDocuments(); loadQuizzes(); loadTeacherAttendanceHistory(); });
